components:
  frontend:
    image:
      repository: nginx
      tag: "1.29.0"
  backend:
    image:
      repository: nginx
      pullPolicy: IfNotPresent
      tag: "1.23.4"
  proxy:
    image:
      repository: nginx
      tag: "1.29.0"
  backend:
    image:
      repository: nginx
      tag: "1.29.0"
      pullPolicy: IfNotPresent